import { Nft } from './types'

const KdfnNfts: Nft[] = [
  {
    name: 'The Crimson Cavalry',
    description: 'Banner for The Crimson Cavalry',
    images: {
      lg: 'TheCrimsonCavalryBanner.png',
      md: 'TheCrimsonCavalryBanner.png',
      sm: 'TheCrimsonCavalryBanner.png',
      ipfs: 'https://ipfs.io/ipfs/Qmcu9csnRSx5yVTGyiCvda29w34j22pyRVFXRT5zM2VgaX?filename=The%20Crimson%20Cavalry%20Banner.PNG',
      blur: 'TheCrimsonCavalryBanner.png',
    },
    sortOrder: 999,
    tokenId: 0,
    nftId: 0,
    purchaseTokenName: "SQUIRE",
  },
  {
    name: 'The Royal Guard',
    description: 'Banner for The Royal Guard',
    images: {
      lg: 'TheRoyalGuardBanner.png',
      md: 'TheRoyalGuardBanner.png',
      sm: 'TheRoyalGuardBanner.png',
      ipfs: 'https://ipfs.io/ipfs/QmWEVCaiER7CeKUNxvNDN8hYumDuUqi6B3XAzDxQ2aocU2?filename=The%20Royal%20Guard%20Banner.PNG',
      blur: 'TheRoyalGuardBanner.png',
    },
    sortOrder: 999,
    tokenId: 0,
    nftId: 1,
    purchaseTokenName: "SQUIRE",
  },
  {
    name: 'The Sentinels',
    description: 'Banner for The Sentinels',
    images: {
      lg: 'TheSentinelsBanner.png',
      md: 'TheSentinelsBanner.png',
      sm: 'TheSentinelsBanner.png',
      ipfs: 'https://ipfs.io/ipfs/QmQEas5XL62P9AkKJunY88jR863yGqHtPjgJnA6qiHxj2a?filename=The%20Sentinels%20Banner.PNG',
      blur: 'TheSentinelsBanner.png',
    },
    sortOrder: 999,
    tokenId: 0,
    nftId: 2,
    purchaseTokenName: "SQUIRE",
  },
  {
    name: 'The Silver Sparrows',
    description: 'Banner for The Silver Sparrows',
    images: {
      lg: 'TheSilverSparrowsBanner.png',
      md: 'TheSilverSparrowsBanner.png',
      sm: 'TheSilverSparrowsBanner.png',
      ipfs: 'https://ipfs.io/ipfs/Qmdd2ihK5uGR677ro1r8nQNT5mKAxDja5sqobYcipNJ4wz?filename=The%20Silver%20Sparrows%20Banner.PNG',
      blur: 'TheSilverSparrowsBanner.png',
    },
    sortOrder: 999,
    tokenId: 0,
    nftId: 3,
    purchaseTokenName: "SQUIRE",
  },
  {
    name: 'The Mystics',
    description: 'Banner for The Mystics',
    images: {
      lg: 'TheMysticsBanner.png',
      md: 'TheMysticsBanner.png',
      sm: 'TheMysticsBanner.png',
      ipfs: 'https://ipfs.io/ipfs/QmWRWzAkgMRyXwehDp8o41m4ccXzymvkA5wQToV5eyQG6s?filename=The%20Mystics%20Banner.PNG',
      blur: 'TheMysticsBanner.png',
    },
    sortOrder: 999,
    tokenId: 0,
    nftId: 4,
    purchaseTokenName: "SQUIRE",
  },
  {
    name: 'Shilling to the Moon',
    description: 'Shilling to the Moon',
    images: {
      lg: 'Shilling to the Moon Small.gif',
      md: 'Shilling to the Moon Small.gif',
      sm: 'Shilling to the Moon Small.gif',
      ipfs: 'https://gateway.pinata.cloud/ipfs/QmWSnwv27kqh8N5f8v9UiXbY2uroKsQZrYjdKpzAPBrrkL?image=shilling_to_the_moon.gif',
      blur: 'Shilling to the Moon Small.gif',
    },
    sortOrder: 999,
    tokenId: 0,
    nftId: 5,
    purchaseTokenName: "KNIGHT",
  },
]

export default KdfnNfts
