import { Nft } from './types'

const KotrtNfts: Nft[] = [
  {
    name: 'Sir Galahad',
    description: 'Sir Galahad - #1',
    images: {
      lg: 'SirGalahad.png',
      md: 'SirGalahad.png',
      sm: 'SirGalahad.png',
      ipfs: 'https://ipfs.io/ipfs/QmYpy2cwnZZjokGXNJWceDwyiX1kTztuCNbzoNN84HS1Jf?filename=SirGalahad.png',
      blur: 'SirGalahad.png',
    },
    sortOrder: 999,
    tokenId: 1,
  },
  {
    name: 'Sir Roper',
    description: 'Sir Roper - #2',
    images: {
      lg: 'SirRoper.png',
      md: 'SirRoper.png',
      sm: 'SirRoper.png',
      ipfs: 'https://ipfs.io/ipfs/QmSZJXkxz2vzMPL2vwha8owZMyrfudZEwCKjm9qRu8PFKX?filename=SirRoper.png',
      blur: 'SirRoper.png',
    },
    sortOrder: 999,
    tokenId: 2,
  },
  {
    name: 'Sir Gaheris',
    description: 'Sir Gaheris - #3',
    images: {
      lg: 'SirGaheris.png',
      md: 'SirGaheris.png',
      sm: 'SirGaheris.png',
      ipfs: 'https://ipfs.io/ipfs/QmUp66oApnAm3byaKUiJfWeUx4U2vpdsiuwYRNGzHgBXgp?filename=SirGaheris.png',
      blur: 'SirGaheris.png',
    },
    sortOrder: 999,
    tokenId: 3,
  },
  {
    name: 'Sir Alymere',
    description: 'Sir Alymere - #4',
    images: {
      lg: 'SirAlymere.png',
      md: 'SirAlymere.png',
      sm: 'SirAlymere.png',
      ipfs: 'https://ipfs.io/ipfs/QmaiMjDRdKpxWyS9sUScxVDGsBBiSt73Hd3zfGTj7WEsRS?filename=SirAlymere.png',
      blur: 'SirAlymere.png',
    },
    sortOrder: 999,
    tokenId: 4,
  },
  {
    name: 'Sir Gawain',
    description: 'Sir Gawain - #5',
    images: {
      lg: 'SirGawain.png',
      md: 'SirGawain.png',
      sm: 'SirGawain.png',
      ipfs: 'https://ipfs.io/ipfs/QmXYhVY6Djg8MGpHV8rRCKQK2ikmHo4Df2EpSpvz9cz6Pe?filename=SirGawain.png',
      blur: 'SirGawain.png',
    },
    sortOrder: 999,
    tokenId: 5,
  },
  {
    name: 'Sir Urien',
    description: 'Sir Urien - #6',
    images: {
      lg: 'SirUrien.png',
      md: 'SirUrien.png',
      sm: 'SirUrien.png',
      ipfs: 'https://ipfs.io/ipfs/QmX8NSChQYKfcRKf7CJBC2FCzNsaPxBgCef8aJ3cqQYytK?filename=SirUrien.png',
      blur: 'SirUrien.png',
    },
    sortOrder: 999,
    tokenId: 6,
  },
  {
    name: 'Sir Coyote',
    description: 'Sir Coyote - #7',
    images: {
      lg: 'SirCoyote.png',
      md: 'SirCoyote.png',
      sm: 'SirCoyote.png',
      ipfs: 'https://ipfs.io/ipfs/QmecstG4sNuheN8W6MboSXe9Cr6jVnPPZR9XpSxkHwMJkF?filename=SirCoyote.png',
      blur: 'SirCoyote.png',
    },
    sortOrder: 999,
    tokenId: 7,
  },
  {
    name: 'Sir Goku',
    description: 'Sir Goku - #8',
    images: {
      lg: 'SirGoku.png',
      md: 'SirGoku.png',
      sm: 'SirGoku.png',
      ipfs: 'https://ipfs.io/ipfs/QmUx9FS8NpMDKdCDBUXqA7ADTnRWQkHCQ4v3QTnhr74YdN?filename=SirGoku.png',
      blur: 'SirGoku.png',
    },
    sortOrder: 999,
    tokenId: 8,
  },
  {
    name: 'Sir Balin',
    description: 'Sir Balin - #9',
    images: {
      lg: 'SirBalin.png',
      md: 'SirBalin.png',
      sm: 'SirBalin.png',
      ipfs: 'https://ipfs.io/ipfs/QmWp9KM9YyG4PL8hkUBy7Fk7UxHoeZR9ZP4R564DeoJQQ2?filename=SirBalin.png',
      blur: 'SirBalin.png',
    },
    sortOrder: 999,
    tokenId: 9,
  },
  {
    name: 'Sir Neuromancer',
    description: 'Sir Neuromancer - #10',
    images: {
      lg: 'SirNeuromancer.png',
      md: 'SirNeuromancer.png',
      sm: 'SirNeuromancer.png',
      ipfs: 'https://ipfs.io/ipfs/QmUjFeC4vsF4iY6uD6qwaguTvzAxBE68QJ5VnDL5TeEotq?filename=SirNeuromancer.png',
      blur: 'SirNeuromancer.png',
    },
    sortOrder: 999,
    tokenId: 10,
  },
  {
    name: 'Sir Meme-Lord',
    description: 'Sir Meme-Lord - #11',
    images: {
      lg: 'SirMeme-Lord.png',
      md: 'SirMeme-Lord.png',
      sm: 'SirMeme-Lord.png',
      ipfs: 'https://ipfs.io/ipfs/QmcCXymgiAEGDEbyDGjcqnmvsy51RmifWaNkV2Le6hmjnX?filename=SirMeme-Lord.png',
      blur: 'SirMeme-Lord.png',
    },
    sortOrder: 999,
    tokenId: 11,
  },
  {
    name: 'Sir Carti',
    description: 'Sir Carti - #12',
    images: {
      lg: 'SirCarti.png',
      md: 'SirCarti.png',
      sm: 'SirCarti.png',
      ipfs: 'https://ipfs.io/ipfs/QmVR9e4KDEt71Fq7K1TmYyzQMQXTAMzEAd86M41fi8VgqX?filename=SirCarti.png',
      blur: 'SirCarti.png',
    },
    sortOrder: 999,
    tokenId: 12,
  }
]

export default KotrtNfts
